"""Reproducible workflow for "Targeted Learning for Inference on Data Fairness".

Conceptual flow:
    raw inputs (data/raw)
      -> generated intermediates (data/generated)
      -> final figures and tables (results/)

Run everything:           uv run snakemake --cores 1
Rebuild one rule:         uv run snakemake --cores 1 --forcerun <rule>
Validate generated data:  uv run snakemake --cores 1 validate

Expensive simulation/analysis outputs are marked protected() so they are not
regenerated by accident; use --forcerun to rebuild them deliberately.
"""

import os

# Interpreter used for each step. Override with TLFAIR_PYTHON if needed.
PYTHON = os.environ.get("TLFAIR_PYTHON", ".venv/bin/python")
RUN = f"PYTHONPATH=. {PYTHON}"

# CPU parallelism for the expensive rules (perm-importance fits and CMI sims).
# Default is serial (1) so a plain run is unchanged; on a fat node request cores
# and matching workers, e.g.:
#   uv run snakemake --cores 64 --config njobs=64 analyze_adult
# Each expensive rule declares threads: NJOBS, so Snakemake runs them one at a
# time (each reserving all the cores) rather than co-scheduling them.
NJOBS = int(config.get("njobs", 1))
# Memory budget (GB) for concurrent knncmi distance arrays in sim_cmi; caps the
# comparison workers at large n to avoid OOM (~4 GB per worker at n=10000).
COMPARE_MEM_GB = float(config.get("compare_mem_gb", 16))

FIGURES = [
    "results/figures/fig1_parity.pdf",
    "results/figures/fig2_robust_coverage.pdf",
    "results/figures/fig3_variance.pdf",
    "results/figures/fig4_cmi_error.pdf",
    "results/figures/fig4_cmi_coverage.pdf",
    "results/figures/fig5_importance.pdf",
]

TABLES = [
    "results/data/table1_inference.csv",
    "results/data/table1_inference.tex",
    "results/data/table2_cmi_truth.csv",
    "results/data/table2_cmi_truth.tex",
]


rule all:
    input:
        FIGURES + TABLES


# ----------------------------------------------------------------------------
# data/raw: capture external inputs
# ----------------------------------------------------------------------------
rule download_adult:
    output:
        "data/raw/adult.csv"
    shell:
        "{RUN} analysis/download_adult/run.py --output {output}"


rule download_law:
    output:
        "data/raw/law.csv"
    shell:
        "{RUN} analysis/download_law/run.py --output {output}"


# ----------------------------------------------------------------------------
# data/generated: simulation and analysis intermediates
# ----------------------------------------------------------------------------
rule sim_parity:
    output:
        fig1="data/generated/parity_fig1.csv",
        fig3="data/generated/parity_fig3.csv",
    shell:
        "{RUN} analysis/sim_parity/run.py "
        "--fig1-output {output.fig1} --fig3-output {output.fig3}"


rule sim_robust:
    output:
        protected("data/generated/robust_res.csv")
    shell:
        "{RUN} analysis/sim_robust/run.py --output {output}"


rule sim_cmi:
    output:
        coverage=protected("data/generated/cmi_coverage.csv"),
        compare=protected("data/generated/cmi_compare.csv"),
        truth=protected("data/generated/truth_dict.pkl"),
        timing=protected("data/generated/cmi_timing.pkl"),
    threads: NJOBS
    shell:
        "{RUN} analysis/sim_cmi/run.py "
        "--n-jobs {threads} --compare-mem-gb {COMPARE_MEM_GB} "
        "--coverage-output {output.coverage} "
        "--compare-output {output.compare} "
        "--truth-output {output.truth} "
        "--timing-output {output.timing}"


rule analyze_adult:
    input:
        "data/raw/adult.csv"
    output:
        protected("data/generated/adult_results.pkl")
    threads: NJOBS
    shell:
        "{RUN} analysis/analyze_adult/run.py --input {input} --output {output} "
        "--cache-importance --n-jobs {threads}"


rule analyze_law:
    input:
        "data/raw/law.csv"
    output:
        protected("data/generated/law_results.pkl")
    threads: NJOBS
    shell:
        "{RUN} analysis/analyze_law/run.py --input {input} --output {output} "
        "--cache-importance --n-jobs {threads}"


# ----------------------------------------------------------------------------
# results/: final figures and tables
# ----------------------------------------------------------------------------
rule fig1_parity:
    input:
        "data/generated/parity_fig1.csv"
    output:
        "results/figures/fig1_parity.pdf"
    shell:
        "{RUN} analysis/fig1_parity/run.py --input {input} --output {output}"


rule fig2_robust:
    input:
        "data/generated/robust_res.csv"
    output:
        "results/figures/fig2_robust_coverage.pdf"
    shell:
        "{RUN} analysis/fig2_robust/run.py --input {input} --output {output}"


rule fig3_variance:
    input:
        "data/generated/parity_fig3.csv"
    output:
        "results/figures/fig3_variance.pdf"
    shell:
        "{RUN} analysis/fig3_variance/run.py --input {input} --output {output}"


rule fig4_cmi:
    input:
        coverage="data/generated/cmi_coverage.csv",
        compare="data/generated/cmi_compare.csv",
        truth="data/generated/truth_dict.pkl",
    output:
        error="results/figures/fig4_cmi_error.pdf",
        coverage="results/figures/fig4_cmi_coverage.pdf",
    shell:
        "{RUN} analysis/fig4_cmi/run.py "
        "--coverage-input {input.coverage} "
        "--compare-input {input.compare} "
        "--truth-input {input.truth} "
        "--error-output {output.error} "
        "--coverage-output {output.coverage}"


rule fig5_importance:
    input:
        adult="data/generated/adult_results.pkl",
        law="data/generated/law_results.pkl",
    output:
        "results/figures/fig5_importance.pdf"
    shell:
        "{RUN} analysis/fig5_importance/run.py "
        "--adult-input {input.adult} --law-input {input.law} --output {output}"


rule table1_inference:
    input:
        adult="data/generated/adult_results.pkl",
        law="data/generated/law_results.pkl",
    output:
        csv="results/data/table1_inference.csv",
        tex="results/data/table1_inference.tex",
    shell:
        "{RUN} analysis/table1_inference/run.py "
        "--adult-input {input.adult} --law-input {input.law} "
        "--csv-output {output.csv} --tex-output {output.tex}"


rule table2_cmi_truth:
    input:
        "data/generated/truth_dict.pkl"
    output:
        csv="results/data/table2_cmi_truth.csv",
        tex="results/data/table2_cmi_truth.tex",
    shell:
        "{RUN} analysis/table2_cmi_truth/run.py "
        "--input {input} --csv-output {output.csv} --tex-output {output.tex}"


# ----------------------------------------------------------------------------
# Optional: validate generated artifacts
# ----------------------------------------------------------------------------
rule validate:
    input:
        "data/generated/robust_res.csv",
        "data/generated/cmi_coverage.csv",
        "data/generated/cmi_compare.csv",
        "data/generated/truth_dict.pkl",
        "data/generated/adult_results.pkl",
        "data/generated/law_results.pkl",
    shell:
        "{RUN} analysis/tools/validate.py data/generated"
